# Generated by Django 5.0.7 on 2024-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='DateOfBirth',
            new_name='dateofbirth',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Picture',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='jhon.jhon@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.CharField(default='choisi une image', max_length=30),
        ),
    ]
