# Generated by Django 5.0.7 on 2024-08-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_rename_dateofbirth_profile_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='John', max_length=30),
        ),
    ]
