# Generated by Django 5.0.7 on 2024-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_rename_username_profile_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sexe',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Client', max_length=10),
        ),
    ]
