# Generated by Django 5.0.7 on 2024-08-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_profile_dateofbirth_profile_email_profile_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
