# Generated by Django 5.0.7 on 2024-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_remove_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client')], default='Client', max_length=20),
        ),
    ]
